### ISSUE TITLE
Playlist alert, movie offer module, movie title

### ISSUE THREAD

**Issue by MaximeRF** [RaitaroH/YouTube-DeepDark#21]
@RaitaroH  Here are some issues and the rulesets to fix them, I let you decide where to insert them:

![playlist alert](https://user-images.githubusercontent.com/12028968/62819316-c008e980-bb53-11e9-84e6-9551ddde774e.png)

```css
ytd-alert-with-button-renderer[type="INFO"]
{
	background-color: var(--hover-background) !important;
}
ytd-alert-with-button-renderer[type="INFO"] #text.ytd-alert-with-button-renderer
{
	color: var(--main-text) !important;
}
```

![movies](https://user-images.githubusercontent.com/12028968/62819404-1c203d80-bb55-11e9-92be-987dfdf3dbb5.png)

```css
#header.ytd-movie-offer-module-renderer
{
	background-color: var(--second-background) !important;
}
ytd-button-renderer.ytd-movie-offer-module-renderer.style-primary[is-paper-button] {
	background-color: var(--main-color) !important;
}
#wide-clickable-area.ytd-movie-offer-module-renderer {
	background-color: var(--hover-background) !important;
}
#info.ytd-movie-offer-module-renderer {
	color: var(--main-text) !important;
}
h3.ytd-compact-movie-renderer {
	color: var(--main-text) !important;
}
```
