### ISSUE TITLE
Create playlist form

### ISSUE THREAD

**Issue by MaximeRF** [RaitaroH/YouTube-DeepDark#22]
@RaitaroH  These are the rulesets to fix the form that appears when we click the "Save" button to add the video we are watching to a playlist.

![create playlist form](https://user-images.githubusercontent.com/12028968/62834561-b0220000-bc4e-11e9-9d59-73d88bfd797f.png)

```css
#create-playlist-form .input-content.paper-input-container label
{
	color: var(--main-text) !important;
}

#create-playlist-form input.style-scope.paper-input::placeholder
{
	color: var(--dimmer-text) !important;
}

#create-playlist-form .underline.is-highlighted.paper-input-container .focused-line.paper-input-container
{
    border-bottom-color: var(--main-text) !important;
}

#create-playlist-form #label.ytd-privacy-dropdown-item-renderer
{
	color: var(--main-text) !important;
}

#create-playlist-form ytd-privacy-dropdown-item-renderer.iron-selected
{
	background-color: var(--hover-background) !important;
}
```
