### ISSUE TITLE
YouTube new update: Ambient mode

### ISSUE THREAD

**Issue by BobbyWibowo** [RaitaroH/YouTube-DeepDark#77]
Hi there, it seems we're getting more and more "material-ish" updates to YouTube,
and one of the recent changes seem to be dynamic backlight thingy

https://user-images.githubusercontent.com/9364930/199154708-cce99ff8-99a2-4882-95f3-ea10417f5ac4.mp4

(ignore the fps, it was some recording setting issue)

Unfortunately, some sections currently have fixed backgrounds with the userstyle active:

![image](https://i.fiery.me/dCmR.png)

**Comment by BobbyWibowo** [comment]
If it hasn't shown for you, it seems it's a new option on the player, called "Ambient mode"

![image](https://i.fiery.me/N1Al.png)

I bandaged mine with the following, but I'm not familiar enough with the rest of the styling to say if that won't cause any other issues:
```css
ytd-watch-flexy[cinematics-enabled] [class*="ytd-watch-flexy"] {
	background-color: unset !important;
}
```

**Comment by RaitaroH** [comment]
As I am testing youtube in light mode (to spot any issues) I didn't have this.
It seems it only shows up if after I enable dark theme in youtube.

Anyhow, this is better on my end:
```css
	#cinematics.ytd-watch-flexy
	{
		display: none !important;
	}
```

I am not sure if I should just remove this entirely... or add a toggle for those who would want to keep it. Any thoughts?
